const collectionActionTypes = {
    
    UPDATE_FILTER: 'UPDATE_FILTER',
    UPDATE_SORT_ORDER: 'UPDATE_SORT_ORDER',
    
    FETCH_POSTS_START: 'FETCH_POSTS_START',
    FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS',
    FETCH_POSTS_FAILURE: 'FETCH_POSTS_FAILURE',

    UPDATE_POST_START: 'UPDATE_POST_START',
    UPDATE_POST_SUCCESS: 'UPDATE_POST_SUCCESS',
    UPDATE_POST_FAILURE: 'UPDATE_POST_FAILURE',

    
}


export default collectionActionTypes;

