const collectionActionTypes = {
    
    UPDATE_FILTER: 'UPDATE_FILTER',
    UPDATE_SORT_ORDER: 'UPDATE_SORT_ORDER',
    
    FETCH_POSTS_START: 'FETCH_POSTS_START',
    FETCH_POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS',
    FETCH_POSTS_FAILURE: 'FETCH_POSTS_FAILURE',

    
}


export default collectionActionTypes;

