const notificationTypes = {
    
    CREATE_NOTIFICATION_START: 'CREATE_NOTIFICATION_START',
    CREATE_NOTIFICATION_SUCCESS: 'CREATE_NOTIFICATION_SUCCESS',
    CREATE_NOTIFICATION_FAILURE: 'CREATE_NOTIFICATION_FAILURE',

    FETCH_NOTIFICATION_START: 'FETCH_NOTIFICATION_START',
    FETCH_NOTIFICATION_SUCCESS: 'FETCH_NOTIFICATION_SUCCESS',
    FETCH_NOTIFICATION_FAILURE: 'FETCH_NOTIFICATION_FAILURE',

    REMOVE_NOTIFICATION_START: 'REMOVE_NOTIFICATION_START',
    REMOVE_NOTIFICATION_SUCCESS: 'REMOVE_NOTIFICATION_SUCCESS',
    REMOVE_NOTIFICATION_FAILURE: 'REMOVE_NOTIFICATION_FAILURE',


};

export default notificationTypes;

